### ISSUE TITLE
Suggestion - instead of strong, use spans

### ISSUE THREAD

**Issue by jzhu01** [altoole/Help#5]
Seen here: https://github.com/altoole/Help/blob/master/Project/DasmotosArtsandCrafts/index.html#L15

Since strong is a stylistic tag, and then you chose to add the style tag in the HTML, I recommend against this. We want to keep our html strictly content, and CSS strictly styling. This way it's easier for other people to review our code. I would recommend using spans and applying a class on them, then giving the class a styling in the CSS.

**Comment by altoole** [comment]
I love this, I knew there had to be a better way to do this! Thanks!
