### ISSUE TITLE
SUMMARY: Meets Expectations

### ISSUE THREAD

**Issue by jzhu01** [altoole/Help#6]
Great job on this project! I really liked your usage of divs, and how you styled the font-family using the html selector. In terms of improvement, I recommend removing the font-weight:bold on your h1 and h2s, reducing repetitive code in your CSS, as well as using span instead of strong tags.

If you’re in the mood for a challenge...I would look into adding more items under each section and finding a nice way to lay them out. Here's a link to get you started - https://www.w3schools.com/css/css_rwd_grid.asp. Keep up the neat work! ^_^

**Comment by altoole** [comment]
Thanks, I will look into the grids. I knew they existed I just didn't think I was there yet!
